---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmprssr
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      function: kmprssr
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: processor
        image: fbiville/processor:grpc
        imagePullPolicy: Always
        env:
        - name: FUNCTION
          value: localhost:8080
        - name: INPUTS
          value: liiklus.default.svc.cluster.local:6565/numbers
        - name: OUTPUTS
          value: liiklus.default.svc.cluster.local:6565/squares
        - name: GROUP
          value: kmprssr
      - name: function
        image: ericbottard/kmprssr:grpc
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
